name: Request to run a new node
description: Create a new issue if you would like to run new Flow Validator node(s)
title: "<Replace this with your organization name e.g. ABCD Inc.>"
projects: ["Flow Node Operation"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following details
  - type: input
    id: name
    attributes:
      label: Name
      description: Your full name
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: discord
    attributes:
      label: Discord ID
      description: What is your Discord ID?
    validations:
      required: true
  - type: checkboxes
    id: role
    attributes:
      label: What node role are you interested in operating?
      description: You may select more than one.
      options:
        - label: Collection
        - label: Consensus
        - label: Verification
        - label: Execution      
  - type: textarea
    id: more_info
    attributes:
      label: Please tell us more about why you want to run node(s) and any other relevant information.
  - type: textarea
    id: flowproject
    attributes:
      label: Please provide links of what you’re currently working on in the context of Flow
      description: This can be a project idea, link to the playground with a contract you’re working on, a github repo with a dapp you’re building, or anything else that indicates what you’re sharing with the community.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: |
        Thank you for filling out the issue.
  - type: markdown
    attributes:
      value: |
        "What happens next?" |
        "The Flow Governance Working Group will review this issue and reach out to you" |
        "You can also checked the status of the issue under the project [Flow Validator](https://github.com/orgs/onflow/projects/42) project
